--insert into usuario (nome, nascimento, genero) values ('Pedro', '19/08/1989', 'M')
--insert into usuario (nome, nascimento, genero) values ('João', '19/08/1989', 'M')
--insert into usuario (nome, nascimento, genero) values ('Ariel', '19/08/1989', 'M')
